### ISSUE TITLE
Component PlayerModel

### ISSUE THREAD

**Issue by PierreHervelin** [PierreHervelin/projet2-metaverse#31]
(A voir si c'est possible @Ki2lian)
Le PlayerModel implémenterai seulement le mesh, avec une position, un model, une animation etc...
Le Player implémenterai toute la logique d'action de l'utilisateur sur le PlayerModel.
Le joueur qu'on contrôle serait un Player, les autres joueurs seraient des PlayerModel

**Comment by Ki2lian** [comment]
done
